### ISSUE TITLE
Successful registration doesn't result in a success email

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#8] opened 2015-08-07 21:48 UTC
_From @talumbau on July 21, 2015 18:21_

When you successfully register, you should get an email that includes your new password, but it turns out you just get a second email that looks just like the first one (so it doesn't include your new password). 

_Copied from original issue: OpenSourcePolicyCenter/webapp#239_

**Comment by ospc-auto** [comment] 2015-08-07 21:48
_From @mistakevin on July 29, 2015 22:4_

taking this per @talumbau request

**Comment by mistakevin** [comment] 2015-08-31 22:04
I don't believe this is fixed

**Comment by talumbau** [comment] 2015-09-11 01:54
this is a duplicate of https://github.com/OpenSourcePolicyCenter/webapp-public/issues/4

**Closed by talumbau** 2015-09-11 01:54 UTC
Labels: bug, duplicate
