### ISSUE TITLE
PE model freezing

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#296] opened 2016-08-09 21:43 UTC
The PE model is freezing midway through on TB. 

You can follow [this reform](http://www.ospc.org/taxbrain/4813/), for example, to the PE page, and run a simulation. It freezes with both .4 and .55 substitution elasticities. 

I've also tried with simpler reforms.

cc @talumbau

**Comment by talumbau** [comment] 2016-08-09 22:02
confirmed. This is the error:

```
  calc3 = calc3.behavior.response(calc1, calc3)
  File "/home/ubuntu/miniconda2/envs/aei_dropq/lib/python2.7/site-packages/taxcalc/behavior.py", line 148, in response
    calc_y_behv = Behavior._update_ordinary_income(taxinc_chg, calc_y_behv)
  File "/home/ubuntu/miniconda2/envs/aei_dropq/lib/python2.7/site-packages/taxcalc/behavior.py", line 205, in _update_ordinary_income
    assert np.allclose(delta_income, delta_wage + delta_oinc + delta_ided)
AssertionError
```

I recall some recent changes to this part of the code. I'll create an issue on Tax-Calculator to see if `dropq` is still doing things in the recommended way.

**Comment by talumbau** [comment] 2016-08-10 02:33
I can confirm that this is due to the bug in Tax-Calculator version 0.6.5 that was found and fixed. It was fixed in this commit:

https://github.com/open-source-economics/Tax-Calculator/commit/be48381574e4b7bf0f75350f8c4a604e20b8d8d1

by @martinholmer. When I sync to that commit and run [this gist](https://gist.github.com/talumbau/7958154241378af235c2dba7674d6823) which is the reform from [TaxBrain 4813](http://www.ospc.org/taxbrain/4813/) the code executes without error. If I use version 0.6.5 of Tax-Calculator, I get the assertion above. The same is true if I run version 0.6.5 of Tax-Calculator with dropq master and then with a version of Tax-Calculator at commit be48381574e4b7bf0f75350f8c4a604e20b8d8d1
 or later.

It looks like `dropq` is still using this style of running the behavior code:

```
calc3 = calc3.behavior.response(calc1, calc3)
```

instead of the new style in the current test_behavior.py:

```
calc3 = Behavior.response(calc1, calc3)
```

but making this change has no change in the outcome. This issue has revealed that we don't handle errors properly for microsim results. This exception should have been caught and then a failure message should be given to the user. But, in any case, this partial equilibrium run will succeed when we deploy the new version of Tax-Calculator.

**Comment by MattHJensen** [comment] 2016-08-10 13:33
> But, in any case, this partial equilibrium run will succeed when we deploy the new version of Tax-Calculator.

Ok. Thanks a lot for figuring that out. 

> This exception should have been caught and then a failure message should be given to the user.

Would this be something to address in https://github.com/open-source-economics/Tax-Calculator/issues/811, or is it more specific?

**Comment by talumbau** [comment] 2016-08-10 13:38
It's more on the AWS side of things. We properly handle OGUSA job failures (which are failed "tasks" in celery) but we don't handle them properly for microsim. Essentially, when we ask if a job is ready, the possible responses are YES, NO, and FAIL. OGUSA jobs can properly respond with FAIL right now. Microsim only responds with YES or NO right now. I will add the logic to allow them to respond with FAIL.

**Comment by MattHJensen** [comment] 2016-08-10 13:46
Ah. Ok

**Comment by talumbau** [comment] 2016-08-10 17:36
TaxBrain has been updated with Tax-Calculator 0.6.6. I was able to run the reform from the microsim listed above (4813) linked to a PE dynamic run and got these results:

http://www.ospc.org/dynamic/behavior_results/175/

I'll leave this open for a while longer, but unless other issues show up I will close.

**Closed** 2016-08-10 18:42 UTC
Labels: bug
