### ISSUE TITLE
running multiple TaxBrain jobs in one browser session produces incorrect results

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#87] opened 2015-10-26 14:11 UTC
See 

Three reforms with Personal exemption increased to 5000 and growth as specified:

http://www.ospc.org/taxbrain/553/  No change to CBO growth
http://www.ospc.org/taxbrain/554/  CBO growth replaced with 0.01
http://www.ospc.org/taxbrain/555/ 0.1 added to CBO growth

Results are the same. 

@Amy-Xu, could you post 
a) what these results should be using tax-calculator master locally. 
b) what these results should be using dropq master locally.

**Comment by MattHJensen** [comment] 2015-10-26 14:14
Just updated to note that _factor_adjustment also seems not to be working.

**Comment by talumbau** [comment] 2015-10-26 14:18
So you are saying that these results:
http://www.ospc.org/taxbrain/556/
http://www.ospc.org/taxbrain/557/

are not enough to demonstrate that growth is working. Hmm.. I thought this was the example you were using previously to determine things were not working - personal exemption at one value, then two different specified growth percentages, and then confirming that the revenue estimates were different.

**Comment by talumbau** [comment] 2015-10-26 14:31
just to be clear: 556 and 557 specify the same personal exemption, but a different replacement CBO growth rate - one is 6%, the other 3%. The revenue estimates are different for each of the 10 years. So in order to proceed with a fix here, I need to know what a better test would be. It would also help with my own personal knowledge to understand why that test is not a good one, but in terms of testing the deployment, I do need a test - and it seems I need a better one than what I used yesterday.

**Comment by MattHJensen** [comment] 2015-10-26 14:33
I am not sure what is going on yet - I don't know why 556 and 557 are generating different results but not (553 and 554) or (554 and 555) or (560 and 561). In each of these cases we are doing pretty much the same thing: set an exemption change and then use default or modified growth. I am investigating.

**Comment by MattHJensen** [comment] 2015-10-26 14:41
This is one issue, but I've verified that it is not the entire problem:

 If I add a number without toggling the radio button like this
![image](https://cloud.githubusercontent.com/assets/8301092/10731746/3b8bd650-7bcd-11e5-847d-78fc57171662.png)
Then when I toggle the radio button it erases the change I had made. 
![image](https://cloud.githubusercontent.com/assets/8301092/10731768/50b69d80-7bcd-11e5-9322-f82b08e2567a.png)

**Comment by MattHJensen** [comment] 2015-10-26 14:46
@talumbau, when I click "edit parameters" for 556 and 557 (the two you generated), and then rerun them, both scenarios generate the same output, contrary to your experience. See 564 and 565. 

Just to be clear, the work flow is:

a) open these pages:
http://www.ospc.org/taxbrain/556/
http://www.ospc.org/taxbrain/557/
b) Click edit parameters for each
c) Click show me the results for each.

**Comment by talumbau** [comment] 2015-10-26 14:52
that is mysterious. I will investigate. can you create a new scenario with my figures and reproduce the results? I just generated them this morning based on the testing I did last night. It would be interesting to see if you would be unable to reproduce (i.e. get different revenue estimates for 3 and 6 percent growth)

**Comment by MattHJensen** [comment] 2015-10-26 15:02
Interesting! I can reproduce if I run them both separately, run one, let it finish, run the other (in separate tabs, but sequentially). But if I try to run them both at the same time from different tabs, it doesn't work.

**Comment by talumbau** [comment] 2015-10-26 15:22
Ah, yes, we keep the job IDs (each year of the calculation has its own job ID) in the `session` which is shared across tabs. To do what you are doing, you would probably need to open an Incognito window, but I have not tested that. We could make a change as suggested here:

http://stackoverflow.com/questions/368653/how-to-differ-sessions-in-browser-tabs

but we might instead just nix the idea of putting the job IDs in the `session` variable. I can investigate if this is a desired behavior.

**Comment by talumbau** [comment] 2015-10-26 15:28
It seems likely that people will want to try to use TaxBrain this way (set up a few runs in different tabs and just say 'go' on each one), and it's not possible to stop them from doing so even though it's not set up to work that way, so I think we will need a solution here.

**Comment by talumbau** [comment] 2015-10-26 16:04
I can confirm that if you sequentially do Matt's suggested calculations (5000 for personal exemption + CBO growth, then 5000 for personal exemption + 0.01 replacement for CBO growth) you get different revenue projections:

http://www.ospc.org/taxbrain/574/
http://www.ospc.org/taxbrain/575/

so I think we should re-title this issue: "running multiple TaxBrain jobs in one browser session produces incorrect results" or something similar.

**Comment by talumbau** [comment] 2015-10-27 03:07
closed via https://github.com/OpenSourcePolicyCenter/webapp-public/pull/89

**Closed by talumbau** 2015-10-27 03:07 UTC
