### ISSUE TITLE
Cost of capital tables - "major industry" values inconsistent with subindustry results

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/webapp-public#422] opened 2016-11-28 19:03 UTC
@salimfurth points out:

>One thing that’s puzzling me is that a lot of the sector level results seem implausible as averages of their major industry components.
>  
> Considering “baseline” reported results only:
> ·         METR for typically-financed corporate manufacturing is 0.200, but the major industries in manufacturing have METR’s in the range [0.035, 0.199].
> ·         METR for debt-financed corporate manufacturing is 0.086, but the major industries are in [-0.083,0.082]
> o   Across all financing and corp/non-corp columns, the average looks like 100% weight has been assigned to “Chemical products” and some rounding errors or have been introduced.
> ·         METR’s for Information (all columns) are lower than the METR for any of the component major industries.
> ·         METR’s for Professional services (all columns) are lower than the METR for any of the component major industries.
> ·         METR’s for Health Care & Social Assistance (all columns) are higher than the METR for any of the component major industries.

I can confirm this behavior on the CCC web app.  However, when I run B-Tax master locally, the results look correct.

**Comment by jdebacker** [comment] 2016-11-28 19:13
To be more specific, I'm not seeing these anomalies in the local results (where the average over the sub-industries is an extreme or outlier of the sub-industry values).  I also find that the values for both major industries and the sub-industries are different from B-Tax master than on  CCC.

**Comment by salimfurth** [comment] 2016-11-29 14:26
The problem appears to exist in "reform" as well as "baseline" cases.

**Comment by jdebacker** [comment] 2016-11-29 15:09
@talumbau, I 'd like to merge B-Tax [PR #117](https://github.com/open-source-economics/B-Tax/pull/117).  I think that PR might necessitate some changes to the output tables since additional assets are included in the 'by asset' output.  Perhaps we can add those lines and take care of this issue and Issue #423 at the same time?

**Comment by MattHJensen** [comment] 2016-11-29 16:11
> @talumbau, I 'd like to merge B-Tax PR #117. I think that PR might necessitate some changes to the output tables since additional assets are included in the 'by asset' output. Perhaps we can add those lines and take care of this issue and Issue #423 at the same time?

Copying @PeterDSteinberg since @talumbau is out of town for a couple of weeks. 

@PeterDSteinberg, if you have a chance to work on this soon it would be great as this is a significant bug.

**Comment by MattHJensen** [comment] 2016-11-29 22:14
> Perhaps we can add those lines and take care of this issue and Issue #423 at the same time?

My preference would be to get the bug fixed by Thursday since I'm giving a presentation at noon. If it is possible to incorporate other changes by then that's great, but the bug is most important.

**Comment by PeterDSteinberg** [comment] 2016-11-29 22:34
@MattHJensen I'll do my best to get this done by noon.  I can fix this and related #423 at same time.  Do you need it deployed to where by noon?  I can confirm I am seeing incorrect summary rows in /ccc METR tables.

**Comment by MattHJensen** [comment] 2016-11-29 22:51
Thanks a lot @PeterDSteinberg. I would need it deployed to www.ospc.org/ccc.  The test app would be ok as well, but given that we currently have significant bugs on ospc.org/ccc, I see no reason not to deploy straight there.

**Comment by jdebacker** [comment] 2016-11-30 01:21
@PeterDSteinberg Feel free to ping me if you have issues.  Try running locally and see if you get was is displayed on the web.  I didn't seem to.

Also, let me know your preference regarding merging B-Tax PR #117.  Given the quick turn around, maybe best to just do this fix, then I'll merge PR #117 and open a web-app issue to update the tables with the new asset categories that will come with that PR.

**Closed** 2016-12-12 20:03 UTC
Labels: bug, CCC, in progress
