### ISSUE TITLE
We should apply the validations specified in params.json to taxsaveinputs fields

### ISSUE THREAD

**Issue by zrisher** [OpenSourcePolicyCenter/webapp-public#52] opened 2015-09-23 17:51 UTC
Per https://github.com/OpenSourcePolicyCenter/Tax-Calculator/issues/331

We'd like to do this both for form POST (server-side) and via javascript (client-side).

**Comment by MattHJensen** [comment] 2015-10-05 18:08
@talumbau, @zrisher, I'm not getting the server-side validation on https://ospc-taxes5.herokuapp.com/taxbrain/. Could you check?

**Comment by talumbau** [comment] 2015-10-06 06:54
Apologies. The test site was not updated for webapp-public master. It is
now. The internet where I am is abysmal. Will try to stay in touch. Please
update on whether the issue is now resolved.

**Comment by talumbau** [comment] 2015-10-06 20:07
@MattHJensen I just did the Django migrations on ospc-taxes5. I ran a policy to the output page, then edited it with the Edit Parameters button, then changed the values to something not allowed, saw the error message, then changed the values to all allowed values and ran to the output page. Let me know if this works for you. thanks!

**Comment by MattHJensen** [comment] 2015-10-06 21:00
Looks great.

**Comment by MattHJensen** [comment] 2016-02-22 15:59
This is resolved with #55. Closing.

**Closed by MattHJensen** 2016-02-22 15:59 UTC
